/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lock } from "./Lock";
export type { SimpleStorage } from "./SimpleStorage";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export { SimpleStorage__factory } from "./factories/SimpleStorage__factory";
