/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface SimpleStorageInterface extends utils.Interface {
  functions: {
    "callPrivatePureFunction(string)": FunctionFragment;
    "compareTwoStrings(string,string)": FunctionFragment;
    "createPerson(string,uint8)": FunctionFragment;
    "favouriteNumber()": FunctionFragment;
    "nameToAge(string)": FunctionFragment;
    "people(uint256)": FunctionFragment;
    "retrieve()": FunctionFragment;
    "store(uint256)": FunctionFragment;
    "viewFunction()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "callPrivatePureFunction"
      | "compareTwoStrings"
      | "createPerson"
      | "favouriteNumber"
      | "nameToAge"
      | "people"
      | "retrieve"
      | "store"
      | "viewFunction"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "callPrivatePureFunction",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "compareTwoStrings",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "createPerson",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "favouriteNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nameToAge",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "people",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "retrieve", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "store",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "viewFunction",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "callPrivatePureFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "compareTwoStrings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPerson",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "favouriteNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nameToAge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "people", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "retrieve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "store", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "viewFunction",
    data: BytesLike
  ): Result;

  events: {};
}

export interface SimpleStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SimpleStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    callPrivatePureFunction(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    compareTwoStrings(
      s1: PromiseOrValue<string>,
      s2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    createPerson(
      _name: PromiseOrValue<string>,
      _age: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    favouriteNumber(overrides?: CallOverrides): Promise<[BigNumber]>;

    nameToAge(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    people(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, number] & { name: string; age: number }>;

    retrieve(overrides?: CallOverrides): Promise<[BigNumber]>;

    store(
      _favouriteNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    viewFunction(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  callPrivatePureFunction(
    name: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  compareTwoStrings(
    s1: PromiseOrValue<string>,
    s2: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  createPerson(
    _name: PromiseOrValue<string>,
    _age: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  favouriteNumber(overrides?: CallOverrides): Promise<BigNumber>;

  nameToAge(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<number>;

  people(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, number] & { name: string; age: number }>;

  retrieve(overrides?: CallOverrides): Promise<BigNumber>;

  store(
    _favouriteNumber: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  viewFunction(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    callPrivatePureFunction(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    compareTwoStrings(
      s1: PromiseOrValue<string>,
      s2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    createPerson(
      _name: PromiseOrValue<string>,
      _age: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    favouriteNumber(overrides?: CallOverrides): Promise<BigNumber>;

    nameToAge(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<number>;

    people(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, number] & { name: string; age: number }>;

    retrieve(overrides?: CallOverrides): Promise<BigNumber>;

    store(
      _favouriteNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    viewFunction(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    callPrivatePureFunction(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    compareTwoStrings(
      s1: PromiseOrValue<string>,
      s2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createPerson(
      _name: PromiseOrValue<string>,
      _age: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    favouriteNumber(overrides?: CallOverrides): Promise<BigNumber>;

    nameToAge(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    people(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    retrieve(overrides?: CallOverrides): Promise<BigNumber>;

    store(
      _favouriteNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    viewFunction(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    callPrivatePureFunction(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    compareTwoStrings(
      s1: PromiseOrValue<string>,
      s2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createPerson(
      _name: PromiseOrValue<string>,
      _age: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    favouriteNumber(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nameToAge(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    people(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    retrieve(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    store(
      _favouriteNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    viewFunction(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
